definitions:
  entity.AddSysRoleDto:
    properties:
      description:
        type: string
      roleKey:
        type: string
      roleName:
        type: string
      status:
        type: integer
    type: object
  entity.DelSysPostDto:
    properties:
      ids:
        items:
          type: integer
        type: array
    type: object
  entity.LoginDto:
    properties:
      id_key:
        description: uuid
        type: string
      image:
        description: 验证码
        maxLength: 6
        minLength: 4
        type: string
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - id_key
    - image
    - password
    - username
    type: object
  entity.SysDept:
    properties:
      children:
        items:
          $ref: '#/definitions/entity.SysDept'
        type: array
      createTime:
        $ref: '#/definitions/util.HTime'
      deptName:
        type: string
      deptStatus:
        type: integer
      deptType:
        type: integer
      id:
        type: integer
      parentId:
        type: integer
    type: object
  entity.SysDeptIdDto:
    properties:
      id:
        type: integer
    type: object
  entity.SysMenu:
    properties:
      children:
        items:
          $ref: '#/definitions/entity.SysMenu'
        type: array
      createTime:
        $ref: '#/definitions/util.HTime'
      icon:
        type: string
      id:
        type: integer
      menuName:
        type: string
      menuStatus:
        type: integer
      menuType:
        type: integer
      parentId:
        type: integer
      sort:
        type: integer
      url:
        type: string
      value:
        type: string
    type: object
  entity.SysMenuIdDto:
    properties:
      id:
        type: integer
    type: object
  entity.SysPost:
    properties:
      createTime:
        $ref: '#/definitions/util.HTime'
      id:
        type: integer
      postCode:
        type: string
      postName:
        type: string
      postStatus:
        type: integer
      remark:
        type: string
    type: object
  entity.SysPostIdDto:
    properties:
      id:
        type: integer
    type: object
  entity.UpdateSysPostStatusDto:
    properties:
      id:
        type: integer
      postStatus:
        type: integer
    type: object
  entity.UpdateSysRoleDto:
    properties:
      description:
        type: string
      id:
        type: integer
      roleKey:
        type: string
      roleName:
        type: string
      status:
        type: integer
    type: object
  result.Result:
    properties:
      code:
        description: 状态码
        type: integer
      data:
        description: 返回的数据
      message:
        description: 提示信息
        type: string
    type: object
  util.HTime:
    properties:
      time.Time:
        type: string
    type: object
info:
  contact: {}
  description: 后台管理系统API接口文档
  title: 通用后台管理系统
paths:
  /api/captcha:
    get:
      description: 验证码接口
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 验证码接口
  /api/dept/add:
    post:
      description: 新增部门接口
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.SysDept'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 新增部门接口
  /api/dept/delete:
    delete:
      description: 删除部门
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.SysDeptIdDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 删除部门
  /api/dept/info:
    get:
      description: 根据id查询部门
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 根据id查询部门
  /api/dept/list:
    get:
      description: 查询部门列表接口
      parameters:
      - description: 部门名称
        in: query
        name: deptName
        type: string
      - description: 部门状态
        in: query
        name: deptStatus
        type: string
      produces:
      - application/json
      responses: {}
      summary: 查询部门列表接口
  /api/dept/update:
    put:
      description: 修改部门
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.SysDept'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 修改部门
  /api/dept/vo/list:
    get:
      description: 查询部门列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 查询部门列表
  /api/login:
    post:
      description: 用户登录接口
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.LoginDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 用户登录接口
  /api/menu/add:
    post:
      description: 新增菜单接口
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.SysMenu'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 新增菜单接口
  /api/menu/delete:
    delete:
      description: 删除菜单
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.SysMenuIdDto'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 删除菜单
  /api/menu/info:
    get:
      description: 根据id查询菜单
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 根据id查询菜单
  /api/menu/list:
    get:
      description: 查询菜单列表
      parameters:
      - description: MenuName
        in: query
        name: MenuName
        type: string
      - description: MenuStatus
        in: query
        name: MenuStatus
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 查询菜单列表
  /api/menu/update:
    put:
      description: 修改菜单
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.SysMenu'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 修改菜单
  /api/menu/vo/list:
    get:
      description: 查询菜单列表
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 查询菜单列表
  /api/post/add:
    post:
      description: 新增岗位接口
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.SysPost'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 新增岗位接口
  /api/post/batch/delete:
    delete:
      description: 批量删除岗位
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.DelSysPostDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 批量删除岗位
  /api/post/delete:
    delete:
      description: 根据id删除岗位
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.SysPostIdDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 根据id删除岗位
  /api/post/info:
    get:
      description: 根据id查询岗位
      parameters:
      - description: ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 根据id查询岗位
  /api/post/list:
    get:
      description: 分页查询岗位列表
      parameters:
      - description: 分页数
        in: query
        name: pageNum
        type: integer
      - description: 每页数
        in: query
        name: pageSize
        type: integer
      - description: 岗位名称
        in: query
        name: postName
        type: string
      - description: 状态：1-> 启用，2->停用
        in: query
        name: postStatus
        type: string
      - description: 开始时间
        in: query
        name: beginTime
        type: string
      - description: 结束时间
        in: query
        name: endTime
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 分页查询岗位列表
  /api/post/update:
    put:
      description: 修改岗位接口
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.SysPost'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 修改岗位接口
  /api/post/updateStatus:
    put:
      description: 岗位状态启用/停用窗口
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.UpdateSysPostStatusDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 岗位状态启用/停用窗口
  /api/post/vo/list:
    get:
      description: 岗位下拉列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 岗位下拉列表
  /api/role/add:
    post:
      description: 新增角色接口
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.AddSysRoleDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 新增角色接口
  /api/role/info:
    get:
      description: 根据id查询角色
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 根据id查询角色
  /api/role/update:
    put:
      description: 修改角色
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.UpdateSysRoleDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 修改角色
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
